/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notepad;

import java.awt.*;

public class App {

    public static void main(String[] args){
        EventQueue.invokeLater(() -> {
            // to run on gui thread instead of main thread
            Notepad n = new Notepad();
            n.setVisible(true);
        });
    }
}
