/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notepad;

import java.awt.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args){

        EventQueue.invokeLater(() -> {
            Notepad n = new Notepad();
            n.setVisible(true);

        });
    }
}
